channels:
  - conda-forge
  - nodefaults

dependencies:
  - python

  # Sphinx dependencies.
  - furo
  - ipython
  - nbsphinx!=0.8.5
  - jinja2=2
  - sphinx
  - sphinx-autoapi
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx-panels
